#!/bin/sh
##########################################################################
# If not stated otherwise in this file or this component's Licenses.txt
# file the following copyright and licenses apply:
#
# Copyright 2015 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##########################################################################
# Usage: confPhp (get|restore|status) [filename]

db_version="1";

########### Functions #################
usage()
{
    echo "Usage: confPhp (get|restore|status) [filename]"
    echo "Example: confPhp get backup.cfg"
}

get ()
{   echo "$db_version" > /nvram/db_version;
	cd /tmp;
	tar -cvf "$1" /nvram/db_version /nvram/syscfg.db /nvram/bbhm_bak_cfg.xml   
	rm /nvram/db_version
}  

restore ()
{	
	mv /nvram/syscfg.db /nvram/syscfg.db.prev
	mv /nvram/bbhm_bak_cfg.xml /nvram/bbhm_bak_cfg.xml.prev
	cd /
	tar -xvf "$1"
	if [ "$?" != "0" ] ; then
		mv /nvram/syscfg.db.prev /nvram/syscfg.db
		mv /nvram/bbhm_bak_cfg.xml.prev /nvram/bbhm_bak_cfg.xml
		echo "CONF_RECOVER_STATUS_FAILURE" > /tmp/confPhp.status
		#my_log(LOG_ERR, "Failed writing back config file");
	fi
    rm /nvram/db_version
	syscfg set restore_reboot true
	touch /nvram/restore_reboot
	echo "CONF_RECOVER_STATUS_NEED_REBOOT" > /tmp/confPhp.status
}  

status ()
{
	if [ -f "/tmp/confPhp.status" ]; 	then
		read -r line < /tmp/confPhp.status
		case $line in
			CONF_RECOVER_STATUS_FAILURE)
			exit 3;
			;;

			CONF_RECOVER_STATUS_NEED_REBOOT)
			exit 2;
			;;
			
			*)
			exit 0;
			;;
		esac
	else
		exit 0;
	fi

}  

########### Parser #################
if [ "$1" == "get" ] ; then
	if [ "$2" == "" ] ; then
		usage;
		exit 0;
	fi
	get $2;
elif [ "$1" == "restore" ] ; then
	if [ "$2" == "" ] ; then
		usage;
		exit 0;
	fi
	restore $2;
elif [ "$1" == "status" ] ; then	
	status;
else 
	usage;
    exit 0;	
fi





